services:
  postgres:
    image: postgres:16
    container_name: arqivo-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: arqivo
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: arqivo-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminsecret
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    # Rely on init container loop rather than healthcheck to keep it simple
    volumes:
      - ./.data/minio:/data

  create-buckets:
    image: minio/mc:latest
    container_name: arqivo-minio-init
    restart: "no"
    depends_on:
      minio:
        condition: service_started
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadminsecret
      S3_BUCKET_US: arqivo-us
      S3_BUCKET_EU: arqivo-eu
    entrypoint: ""
    command: ["/bin/sh", "-c", "until mc alias set local http://minio:9000 $$MINIO_ACCESS_KEY $$MINIO_SECRET_KEY; do echo waiting for minio...; sleep 1; done && mc mb -p local/$$S3_BUCKET_US || true && mc mb -p local/$$S3_BUCKET_EU || true && mc version enable local/$$S3_BUCKET_US || true && mc version enable local/$$S3_BUCKET_EU || true"]

  api:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    container_name: arqivo-api
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
      create-buckets:
        condition: service_completed_successfully
    environment:
      NODE_ENV: production
      PORT: 3001
      # Auth (dev-friendly)
      STRICT_AUTH: "false"
      DEV_AUTH_BYPASS: "1"
      CLERK_SECRET_KEY: sk_dev_dummy
      # DB
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/arqivo
      ACCOUNT_REGION_DEFAULT: us
      # Redis for rate limiting
      REDIS_URL: redis://redis:6379
      # S3-compatible (MinIO)
      AWS_REGION: us-east-1
      AWS_S3_ENDPOINT: http://minio:9000
      AWS_S3_FORCE_PATH_STYLE: "true"
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadminsecret
      S3_BUCKET_US: arqivo-us
      S3_BUCKET_EU: arqivo-eu
      # Limits / rate
      MAX_BLOB_BYTES: 50000000
      RATE_CAPACITY: 200
      RATE_REFILL: 100
    ports:
      - "3001:3001"
    command: sh -c "node dist/migrate.js && node dist/index.js"

  redis:
    image: redis:7-alpine
    container_name: arqivo-redis
    restart: unless-stopped
    ports:
      - "6380:6379"



