import { z } from 'zod';

const envSchema = z.object({
  NODE_ENV: z.enum(['development','test','production']).default('development'),
  PORT: z.string().default('3001'),
  AWS_REGION: z.string().min(1).default('us-east-1'),
  ACCOUNT_REGION_DEFAULT: z.string().default('us'),
  CLERK_SECRET_KEY: z.string().optional(),
  S3_BUCKET_US: z.string().min(1).default('arqivo-us'),
  S3_BUCKET_EU: z.string().min(1).default('arqivo-eu'),
  AWS_S3_ENDPOINT: z.string().optional(),
  AWS_S3_FORCE_PATH_STYLE: z.string().optional(),
  STRICT_AUTH: z.string().optional(),
  REDIS_URL: z.string().optional(),
  WEB_ORIGIN: z.string().optional(),
  DEV_AUTH_BYPASS: z.string().optional(),
  STRIPE_SECRET_KEY: z.string().optional(),
  STRIPE_WEBHOOK_SECRET: z.string().optional(),
  STRIPE_PRICE_STANDARD: z.string().optional(),
  STRIPE_PRICE_PRO: z.string().optional(),
  BILLING_RETURN_URL: z.string().optional(),
  BILLING_CANCEL_URL: z.string().optional(),
  ENTERPRISE_UPLOAD_CONCURRENCY: z.string().optional(),
  ENABLE_OTEL: z.string().optional(),
  OTEL_EXPORTER_OTLP_ENDPOINT: z.string().optional(),
  OTEL_SERVICE_NAME: z.string().optional(),
  QUEUE_MAX_DEPTH: z.string().optional(),
  EXTRACT_CONCURRENCY: z.string().optional(),
  WEBHOOK_CONCURRENCY: z.string().optional(),
  CLEANUP_CONCURRENCY: z.string().optional(),
  BYTES_CAPACITY: z.string().optional(),
  BYTES_REFILL_PER_SEC: z.string().optional(),
});

export const env = envSchema.parse({
  NODE_ENV: process.env.NODE_ENV,
  PORT: process.env.PORT,
  AWS_REGION: process.env.AWS_REGION,
  ACCOUNT_REGION_DEFAULT: process.env.ACCOUNT_REGION_DEFAULT,
  CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
  S3_BUCKET_US: process.env.S3_BUCKET_US,
  S3_BUCKET_EU: process.env.S3_BUCKET_EU,
  AWS_S3_ENDPOINT: process.env.AWS_S3_ENDPOINT,
  AWS_S3_FORCE_PATH_STYLE: process.env.AWS_S3_FORCE_PATH_STYLE,
  STRICT_AUTH: process.env.STRICT_AUTH,
  REDIS_URL: process.env.REDIS_URL,
  WEB_ORIGIN: process.env.WEB_ORIGIN,
  DEV_AUTH_BYPASS: process.env.DEV_AUTH_BYPASS,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
  STRIPE_PRICE_STANDARD: process.env.STRIPE_PRICE_STANDARD,
  STRIPE_PRICE_PRO: process.env.STRIPE_PRICE_PRO,
  BILLING_RETURN_URL: process.env.BILLING_RETURN_URL,
  BILLING_CANCEL_URL: process.env.BILLING_CANCEL_URL,
  ENTERPRISE_UPLOAD_CONCURRENCY: process.env.ENTERPRISE_UPLOAD_CONCURRENCY,
  ENABLE_OTEL: process.env.ENABLE_OTEL,
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env.OTEL_EXPORTER_OTLP_ENDPOINT,
  OTEL_SERVICE_NAME: process.env.OTEL_SERVICE_NAME,
  QUEUE_MAX_DEPTH: process.env.QUEUE_MAX_DEPTH,
  EXTRACT_CONCURRENCY: process.env.EXTRACT_CONCURRENCY,
  WEBHOOK_CONCURRENCY: process.env.WEBHOOK_CONCURRENCY,
  CLEANUP_CONCURRENCY: process.env.CLEANUP_CONCURRENCY,
  BYTES_CAPACITY: process.env.BYTES_CAPACITY,
  BYTES_REFILL_PER_SEC: process.env.BYTES_REFILL_PER_SEC,
});
